spring.application.name=RegistroDistribuido-N3
node.id=3
node.port=8083
node.valid-token=TOKEN-SECRETO-2025
node.heartbeat-interval-ms=2000
node.heartbeat-timeout-ms=6000
node.peers[0].id=1
node.peers[0].host=localhost
node.peers[0].port=8081
node.peers[1].id=2
node.peers[1].host=localhost
node.peers[1].port=8082
spring.main.web-application-type=none
